out_dir: results
metric_best: accuracy
dataset:
  format: PyG-TUDataset
  name: ENZYMES
  task: graph
  task_type: classification
train:
  batch_size: 64
  eval_period: 1
  epochs: 200
  repetition: 10
  split_mode: random
  split_ratios: [0.7, 0.15, 0.15]
model:
  type: GAT
  loss_fun: cross_entropy
  graph_pooling: mean
gnn:
  heads: 4
  num_layers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  nhid: 64
  dropout: 0.5
optim:
  clip_grad_norm: True
  optimizer: adam
  weight_decay: 0.0
  base_lr: 0.001
  scheduler: reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 5
  min_lr: 0.00001