out_dir: results
metric_best: ap
dataset:
  format: PyG-LRGBDataset
  name: Peptides-func
  task: graph
  task_type: classification_multilabel
train:
  batch_size: 200
  eval_period: 1
  epochs: 200
  repetition: 5
  split_mode: random
  split_ratios: [0.7, 0.15, 0.15]
model:
  type: GCN
  loss_fun: cross_entropy
  graph_pooling: mean
gnn:
  heads: null
  num_layer: 6
  nhid: 76
  dropout: 0.5
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  # scheduler: cosine_with_warmup
  # warmup_steps: 10
  scheduler: reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 5
  min_lr: 0.00001