out_dir: results
metric_best: ap
dataset:
  format: PyG-LRGBDataset
  name: Peptides-func
  task: graph
  task_type: classification_multilabel
train:
  batch_size: 128
  eval_period: 1
  epochs: 500
  repetition: 10
  split_mode: random
  split_ratios: [0.7, 0.15, 0.15]
model:
  type: GCN
  loss_fun: cross_entropy
  graph_pooling: mean
gnn:
  heads: null
  num_layer: 4
  nhid: 96
  dropout: 0.5
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.0003
  scheduler: steplr
  step_size: 20
  gamma: 0.5