out_dir: results
metric_best: ap
dataset:
  format: PyG-LRGBDataset
  name: Peptides-func
  task: graph
  task_type: classification_multilabel
train:
  batch_size: 128
  eval_period: 1
  epochs: 20
  repetition: 2
  split_mode: random
  split_ratios: [0.7, 0.15, 0.15]
model:
  type: GIN
  loss_fun: cross_entropy
  graph_pooling: mean
gnn:
  heads: null
  num_layers: [1, 2, 3, 4, 5, 6]
  nhid: 96
  dropout: 0.5
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.0003
  scheduler: steplr
  step_size: 50
  gamma: 0.5