out_dir: results
metric_best: ap
wandb:
  use: False
  project: peptides-func
dataset:
  format: PyG-LRGBDataset
  name: Peptides-func
  task: graph
  task_type: classification_multilabel
  transductive: False
  node_encoder: True
  node_encoder_name: Atom+RWSE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,17)
  model: Linear
  dim_pe: 16
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 200
  eval_period: 1
  ckpt_period: 100
  epochs: 200
  repetition: 5
  split_mode: random
  split_ratios: [0.7, 0.15, 0.15]
model:
  type: GPSModel
  loss_fun: cross_entropy
  graph_pooling: mean
gt:
  layer_type: CustomGatedGCN+Transformer
  layers: 6
  n_heads: 4
  dim_hidden: 76  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.1
  attn_dropout: 0.5
  layer_norm: False
  batch_norm: True
gnn:
  head: default
  layers_pre_mp: 0
  layers_post_mp: 1  # Not used when `gnn.head: san_graph`
  dim_inner: 76  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.1
  num_layer: not_specified
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 200
  # scheduler: cosine_with_warmup
  # num_warmup_epochs: 10
  # # step_size: 20
  # # gamma: 0.5
  # warmup_steps: 10
  scheduler: reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 5
  min_lr: 0.00001
