out_dir: results
metric_best: accuracy
wandb:
  use: False
  project: Cora
dataset:
  format: PyG-Planetoid
  name: Cora
  task: node
  task_type: classification
  transductive: True
  node_encoder: True
  node_encoder_name: RWSE
  node_encoder_bn: True
  edge_encoder: False
  edge_encoder_name: DummyEdge
  edge_encoder_bn: False
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,10)
  model: Linear
  dim_pe: 20
  raw_norm_type: BatchNorm
train:
  mode: custom
  sampler: full_batch
  eval_period: 5
  # ckpt_period: 100
  enable_ckpt: False
  epochs: 500
  repetition: 2
  split_mode: random
  split_ratios: [0.7, 0.15, 0.15]
model:
  type: GPSModel
  loss_fun: negative_log_likelihood
  graph_pooling: mean
gt:
  layer_type: GCN+Transformer
  layers: 2
  n_heads: 4
  dim_hidden: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.0
  attn_dropout: 0.5
  layer_norm: False
  batch_norm: False
gnn:
  head: default
  layers_pre_mp: 0
  layers_post_mp: 1  # Not used when `gnn.head: san_graph`
  dim_inner: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
  num_layer: not_specified
optim:
  clip_grad_norm: True
  optimizer: adam
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 500
  scheduler: steplr
  step_size: 50
  gamma: 0.5
